version: '3.7'

services:
  terraform:
    command: sh -c "terraform init && terraform apply -auto-approve"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      TF_VAR_handler: index.handler
      TF_VAR_name: MyFunction
      TF_VAR_runtime: nodejs12.x
    image: 1mill/terraform-sops:alpine-2020-09-05T04-00-37
    volumes:
      - ./services/hello-world:/app
