version: '3.7'

services:
  gateway:
    build: ./services/gateway
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_LAMBDA_ARN: arn:aws:lambda:us-west-2:076550078650:function:deleteThisTesting
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./services/gateway:/app

  hello-world:
    command: index.handler
    environment:
      DOCKER_LAMBDA_STAY_OPEN: 1
    image: lambci/lambda:nodejs12.x
    ports:
      - 9001:9001
    volumes:
      - ./services/hello-world:/var/task:ro,delegated
