version: '3.8'

services:
  rapids:
    image: confluentinc/cp-kafka:5.5.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  emitter:
    command: index.handler
    environment:
      CLOUDEVENTS_RAPIDS_PROTOCOL: kafka
      CLOUDEVENTS_RAPIDS_URLS: rapids:9092
      DOCKER_LAMBDA_STAY_OPEN: 1
    image: lambci/lambda:nodejs12.x
    # image: node:12-alpine
    volumes:
      - ./services/emitter:/var/task
    working_dir: /var/task

  gateway:
    build: ./services/gateway
    depends_on:
      - rapids
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: us-west-1
      AWS_LAMBDA_ARN: arn:aws:lambda:us-west-1:076550078650:function:feature-flags--b7d458f3e160d793fe95236531b81552f52d2208d8df339d3
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CLOUDEVENTS_RAPIDS_PROTOCOL: kafka
      CLOUDEVENTS_RAPIDS_URLS: rapids:9092
    volumes:
      - ./services/gateway:/app

  lambda-h:
    image: docker.pkg.github.com/1mill/experiment-aws-lambda/lambda-hydrator:${VERSION-development}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_LAMBDA_ARN: arn:aws:lambda:us-west-1:076550078650:function:feature-flags--b7d458f3e160d793fe95236531b81552f52d2208d8df339d3
      AWS_REGION: us-west-1
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CLOUDEVENTS_ID: lambda-h-service
      CLOUDEVENTS_PROTOCOL: kafka
      CLOUDEVENTS_TYPES: is-feature-flag-enabled.2020-09-12
      CLOUDEVENTS_URLS: rapids:9092

  hello-world:
    command: index.handler
    environment:
      DOCKER_LAMBDA_STAY_OPEN: 1
    image: lambci/lambda:nodejs12.x
    ports:
      - 9001:9001
    volumes:
      - ./services/hello-world:/var/task

  feature-flags:
    command: index.handler
    environment:
      CLOUDEVENTS_RAPIDS_PROTOCOL: kafka
      CLOUDEVENTS_RAPIDS_URLS: rapids:9092
      DOCKER_LAMBDA_STAY_OPEN: 1
    image: lambci/lambda:nodejs12.x
    # image: node:12-alpine
    ports:
      - 9002:9001
    volumes:
      - ./services/feature-flags:/var/task

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_REQUEST_TIMEOUT: 2000
      ZOOKEEPER_TICK_TIME: 2000
