version: '3.7'

services:
  gateway:
    build: ./services/gateway
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./services/gateway:/app

  hello-world:
    command: index.handler
    image: lambci/lambda:nodejs12.x
    volumes:
      - ./services/hello-world:/var/task:ro,delegated
