version: '3.7'

services:
  gateway:
    build: ./services/gateway
    volumes:
      - ./services/gateway:/app

  hello-world:
    command: index.handler
    image: lambci/lambda:nodejs12.x
    volumes:
      - ./services/hello-world:/var/task:ro,delegated
