version: '3.8'

services:
  app:
    image: docker.pkg.github.com/1mill/experiment-aws-lambda/lambda-hydrator:${VERSION-development}
    build: .
    environment:
      NODE_ENV: develompent
    volumes:
      - ./:/app

  test:
    image: docker.pkg.github.com/1mill/experiment-aws-lambda/lambda-hydrator:${VERSION-development}
    environment:
      NODE_ENV: production
